import PDFDocument from "pdfkit";

export interface PdfReportInput {
  topic: string;
  status: string;
  provider: string;
  isDemo: boolean;
  retrievedCount: number;
  requestedCount: number;
  scoredCount: number;
  unscorableCount: number;
  coverageStart: string | null;
  coverageEnd: string | null;
  averageTopicMatch: number | null;
  relevantPostsPct: number | null;
  similarContentPct: number | null;
  dedupClusterCount: number;
  report: {
    executiveSummary: string;
    keyTakeawaysJson: string[];
    questionsJson: string[];
    limitations: string;
    generatedByProvider: string;
    generatedByModel: string;
  } | null;
  representativePosts: {
    theme: string | null;
    authorName: string;
    authorHandle: string;
    postedAt: string;
    url: string;
    text: string;
    score: number | null;
  }[];
}

const PAGE_MARGIN = 50;

export function renderReportPdf(input: PdfReportInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: "A4", bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).font("Helvetica-Bold").text("TopicPulse Report", { align: "left" });
    doc.fontSize(14).font("Helvetica").fillColor("#1476c4").text(input.topic);
    doc.fillColor("black");
    doc.moveDown(0.5);

    doc.fontSize(9).fillColor("#4d6a8f");
    doc.text(
      `Status: ${input.status}${input.isDemo ? " (demo mode)" : ""} · Provider: ${input.provider} · Retrieved ${input.retrievedCount} of ${input.requestedCount} requested`
    );
    doc.text(`Coverage: ${input.coverageStart ?? "n/a"} to ${input.coverageEnd ?? "n/a"}`);
    doc.text(
      `Average Topic Match: ${input.averageTopicMatch ?? "Not available"}${input.averageTopicMatch !== null ? "%" : ""} · Relevant Posts: ${input.relevantPostsPct ?? "Not available"}${input.relevantPostsPct !== null ? "%" : ""} (of ${input.scoredCount} scored, ${input.unscorableCount} unscorable)`
    );
    doc.text(`Similar Content: ${input.similarContentPct ?? "n/a"}% across ${input.dedupClusterCount} near-duplicate cluster(s)`);
    doc.fillColor("black");
    doc.moveDown();

    if (input.report) {
      section(doc, "Executive Summary");
      doc.fontSize(10).font("Helvetica").text(input.report.executiveSummary, { align: "left" });
      doc.moveDown();
      doc.fontSize(8).fillColor("#4d6a8f").text(
        `Generated by ${input.report.generatedByProvider === "heuristic" ? "a deterministic heuristic (no AI configured/tested)" : `${input.report.generatedByProvider} (${input.report.generatedByModel})`}`
      );
      doc.fillColor("black");
      doc.moveDown();

      if (input.report.keyTakeawaysJson.length > 0) {
        section(doc, "Key Takeaways");
        bulletList(doc, input.report.keyTakeawaysJson);
        doc.moveDown();
      }

      if (input.report.questionsJson.length > 0) {
        section(doc, "Questions People Are Asking");
        bulletList(doc, input.report.questionsJson);
        doc.moveDown();
      }
    }

    if (input.representativePosts.length > 0) {
      section(doc, `Representative Posts (${input.representativePosts.length})`);
      for (const post of input.representativePosts) {
        doc.fontSize(9).font("Helvetica-Bold").fillColor("black").text(`${post.authorName} (@${post.authorHandle})`, { continued: true });
        doc.font("Helvetica").fillColor("#4d6a8f").text(`  ·  ${post.postedAt}  ·  Topic Match: ${post.score ?? "n/a"}`);
        if (post.theme) {
          doc.fontSize(8).fillColor("#1476c4").text(post.theme.toUpperCase());
        }
        doc.fontSize(9).fillColor("black").text(post.text, { align: "left" });
        doc.fontSize(8).fillColor("#1476c4").text(post.url, { link: post.url, underline: true });
        doc.fillColor("black");
        doc.moveDown(0.75);
      }
    }

    if (input.report?.limitations) {
      doc.moveDown();
      section(doc, "Collection Limitations");
      doc.fontSize(9).font("Helvetica").text(input.report.limitations);
    }

    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(7)
        .fillColor("#4d6a8f")
        .text(`TopicPulse · Page ${i + 1} of ${range.count}`, PAGE_MARGIN, doc.page.height - 30, {
          width: doc.page.width - PAGE_MARGIN * 2,
          align: "center",
        });
    }

    doc.end();
  });
}

function section(doc: PDFKit.PDFDocument, title: string) {
  doc.fontSize(13).font("Helvetica-Bold").fillColor("black").text(title);
  doc.moveDown(0.3);
}

function bulletList(doc: PDFKit.PDFDocument, items: string[]) {
  doc.fontSize(9).font("Helvetica");
  for (const item of items) {
    doc.text(`•  ${item}`, { align: "left" });
  }
}
