import { describe, expect, it, vi } from "vitest";
import { generateReport } from "./report";
import { AIProviderError, type AIProvider } from "@/lib/providers/ai/types";

describe("generateReport (heuristic path, no AI configured)", () => {
  it("only cites post ids that were actually collected", async () => {
    const posts = [
      { id: "a1", text: "topicpulse launched a new feature today for developers", authorHandle: "dev1", url: "https://example.com/1", score: 90 },
      { id: "a2", text: "topicpulse launched a new feature today for developers", authorHandle: "dev2", url: "https://example.com/2", score: 85 },
      { id: "a3", text: "totally unrelated content about weekend plans", authorHandle: "dev3", url: "https://example.com/3", score: 20 },
    ];
    const validIds = new Set(posts.map((p) => p.id));
    const report = await generateReport("topicpulse", posts, null);

    for (const theme of report.themes) {
      for (const id of theme.postIds) expect(validIds.has(id)).toBe(true);
    }
    for (const rp of report.representativePosts) {
      expect(validIds.has(rp.postId)).toBe(true);
    }
  });

  it("handles zero collected posts without fabricating a report", async () => {
    const report = await generateReport("topic", [], null);
    expect(report.themes).toHaveLength(0);
    expect(report.representativePosts).toHaveLength(0);
    expect(report.executiveSummary).toMatch(/no posts were collected/i);
  });
});

describe("generateReport (AI configured but the call fails)", () => {
  // Regression test: a report generated by a failed AI call must be labeled as a
  // heuristic fallback (source: "heuristic"), never silently mislabeled as AI-generated
  // just because a provider was configured, and the real failure reason must be visible
  // in limitations rather than swallowed into a generic message.
  it("falls back to the heuristic report and surfaces the specific provider error", async () => {
    const failingProvider: AIProvider = {
      id: "openai",
      label: "OpenAI",
      defaultEndpoint: "https://api.openai.com",
      supportsModelDiscovery: true,
      fallbackModels: [],
      listModels: vi.fn(),
      complete: vi.fn().mockRejectedValue(new AIProviderError("invalid_key", "The API key was rejected.")),
      testConnection: vi.fn(),
    };
    const posts = [{ id: "p1", text: "some post about the topic", authorHandle: "a", url: "https://example.com/1", score: null }];

    const report = await generateReport("topic", posts, { provider: failingProvider, config: { apiKey: "bad", model: "gpt-4o-mini" } });

    expect(report.source).toBe("heuristic");
    expect(report.limitations).toContain("invalid_key");
    expect(report.limitations).toContain("The API key was rejected.");
  });
});
