"use client";

import { useEffect, useMemo, useState } from "react";
import type { RunDetail } from "@/types";
import { PostCard } from "@/components/PostCard";

export const REP_COUNT_OPTIONS = [10, 20, 30, 40, 50] as const;
export type RepCount = (typeof REP_COUNT_OPTIONS)[number];

export function OverviewTab({
  detail,
  repCount,
  onRepCountChange,
}: {
  detail: RunDetail;
  repCount: RepCount;
  onRepCountChange: (n: RepCount) => void;
}) {
  const { report, posts, run } = detail;
  const [page, setPage] = useState(0);

  const themeByPostId = useMemo(() => {
    const map = new Map<string, string>();
    for (const rp of report?.representativePostsJson ?? []) map.set(rp.postId, rp.theme);
    return map;
  }, [report]);

  const sortedByRelevance = useMemo(
    () => [...posts].filter((p) => p.score?.isScorable).sort((a, b) => (b.score?.score ?? 0) - (a.score?.score ?? 0)),
    [posts]
  );

  useEffect(() => setPage(0), [repCount]);

  const totalPages = Math.max(1, Math.ceil(sortedByRelevance.length / repCount));
  const currentPage = Math.min(page, totalPages - 1);
  const pageStart = currentPage * repCount;
  const pageItems = sortedByRelevance.slice(pageStart, pageStart + repCount);

  if (!report) {
    return <p className="rounded-xl border border-border bg-surface p-6 text-sm text-foreground-muted">No report has been generated for this run yet.</p>;
  }

  return (
    <div className="space-y-6">
      <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
        <h2 className="text-lg font-semibold text-foreground">Executive summary</h2>
        <p className="mt-2 whitespace-pre-wrap text-sm text-foreground-muted">{report.executiveSummary}</p>
        <p className="mt-3 text-xs text-foreground-muted">
          Generated by {report.generatedByProvider === "heuristic" ? "a deterministic heuristic (no AI configured)" : `${report.generatedByProvider} (${report.generatedByModel})`} · v{report.version}
        </p>
      </section>

      {report.keyTakeawaysJson.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Key takeaways</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-sm text-foreground-muted">
            {report.keyTakeawaysJson.map((t, i) => (
              <li key={i}>{t}</li>
            ))}
          </ul>
        </section>
      )}

      {report.disagreementsJson.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Areas of disagreement</h2>
          <div className="mt-3 space-y-4">
            {report.disagreementsJson.map((d, i) => (
              <div key={i}>
                <p className="text-sm font-medium text-foreground">{d.topic}</p>
                <div className="mt-1 grid gap-2 sm:grid-cols-2">
                  {d.viewpoints.map((v, j) => (
                    <div key={j} className="rounded-lg bg-surface-muted p-3">
                      <p className="text-sm text-foreground">{v.stance}</p>
                      <p className="mt-1 text-xs text-foreground-muted">{v.postIds.length} supporting post(s)</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {report.questionsJson.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Questions people are asking</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-sm text-foreground-muted">
            {report.questionsJson.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </section>
      )}

      {sortedByRelevance.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <h2 className="text-lg font-semibold text-foreground">Representative posts</h2>
            <div className="flex items-center gap-2">
              <label htmlFor="rep-count" className="text-xs font-medium text-foreground-muted">
                Per page
              </label>
              <select
                id="rep-count"
                value={repCount}
                onChange={(e) => onRepCountChange(Number(e.target.value) as RepCount)}
                className="rounded-lg border border-border bg-background px-2 py-1 text-sm text-foreground outline-none focus-visible:border-primary-400"
              >
                {REP_COUNT_OPTIONS.map((n) => (
                  <option key={n} value={n}>
                    {n}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <p className="mt-1 text-xs text-foreground-muted">Ordered by Topic Match score, highest first.</p>

          <div className="mt-3 space-y-3">
            {pageItems.map((post, i) => {
              const theme = themeByPostId.get(post.id);
              return (
                <div key={post.id}>
                  {theme && <p className="mb-1 text-xs font-medium uppercase tracking-wide text-primary-600">{theme}</p>}
                  <PostCard post={post} index={pageStart + i} />
                </div>
              );
            })}
          </div>

          <div className="mt-4 flex items-center justify-between gap-3 border-t border-border pt-3">
            <p className="text-xs text-foreground-muted">
              Showing {pageItems.length === 0 ? 0 : pageStart + 1}–{pageStart + pageItems.length} of {sortedByRelevance.length}
            </p>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setPage((p) => Math.max(0, p - 1))}
                disabled={currentPage === 0}
                className="rounded-lg border border-border px-3 py-1 text-xs font-medium text-foreground-muted hover:border-primary-300 hover:text-primary-700 disabled:cursor-not-allowed disabled:opacity-40"
              >
                ← Prev
              </button>
              <button
                type="button"
                onClick={() => setPage((p) => Math.min(totalPages - 1, p + 1))}
                disabled={currentPage >= totalPages - 1}
                className="rounded-lg border border-border px-3 py-1 text-xs font-medium text-foreground-muted hover:border-primary-300 hover:text-primary-700 disabled:cursor-not-allowed disabled:opacity-40"
              >
                Next →
              </button>
            </div>
          </div>
        </section>
      )}

      <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
        <h2 className="text-lg font-semibold text-foreground">Collection limitations</h2>
        <p className="mt-2 text-sm text-foreground-muted">{report.limitations}</p>
        <ul className="mt-3 space-y-1 text-xs text-foreground-muted">
          <li>Retrieved {run.retrievedCount} of {run.requestedCount} requested · scored {run.scoredCount} · unscorable {run.unscorableCount}</li>
          <li>
            Similar Content: {run.similarContentPct ?? "n/a"}% across {run.dedupClusterCount} near-duplicate cluster(s)
            {run.similarityMethod ? ` — method: ${run.similarityMethod}, threshold ${run.similarityThreshold}` : ""}. A higher share may indicate
            repetitive or templated posting; it does not by itself prove inauthentic or coordinated activity.
          </li>
          <li>This sample is not necessarily representative of all X users or all discussion of this topic.</li>
        </ul>
      </section>
    </div>
  );
}
