"use client";

import type { RunDetail } from "@/types";
import { PostCard } from "@/components/PostCard";

export function OverviewTab({ detail }: { detail: RunDetail }) {
  const { report, posts, run } = detail;

  if (!report) {
    return <p className="rounded-xl border border-border bg-surface p-6 text-sm text-foreground-muted">No report has been generated for this run yet.</p>;
  }

  const postById = new Map(posts.map((p) => [p.id, p]));

  return (
    <div className="space-y-6">
      <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
        <h2 className="text-lg font-semibold text-foreground">Executive summary</h2>
        <p className="mt-2 whitespace-pre-wrap text-sm text-foreground-muted">{report.executiveSummary}</p>
        <p className="mt-3 text-xs text-foreground-muted">
          Generated by {report.generatedByProvider === "heuristic" ? "a deterministic heuristic (no AI configured)" : `${report.generatedByProvider} (${report.generatedByModel})`} · v{report.version}
        </p>
      </section>

      {report.keyTakeawaysJson.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Key takeaways</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-sm text-foreground-muted">
            {report.keyTakeawaysJson.map((t, i) => (
              <li key={i}>{t}</li>
            ))}
          </ul>
        </section>
      )}

      {report.disagreementsJson.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Areas of disagreement</h2>
          <div className="mt-3 space-y-4">
            {report.disagreementsJson.map((d, i) => (
              <div key={i}>
                <p className="text-sm font-medium text-foreground">{d.topic}</p>
                <div className="mt-1 grid gap-2 sm:grid-cols-2">
                  {d.viewpoints.map((v, j) => (
                    <div key={j} className="rounded-lg bg-surface-muted p-3">
                      <p className="text-sm text-foreground">{v.stance}</p>
                      <p className="mt-1 text-xs text-foreground-muted">{v.postIds.length} supporting post(s)</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {report.questionsJson.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Questions people are asking</h2>
          <ul className="mt-2 list-disc space-y-1.5 pl-5 text-sm text-foreground-muted">
            {report.questionsJson.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </section>
      )}

      {report.representativePostsJson.length > 0 && (
        <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-foreground">Representative posts</h2>
          <div className="mt-3 space-y-3">
            {report.representativePostsJson.map((rp, i) => {
              const post = postById.get(rp.postId);
              if (!post) return null;
              return (
                <div key={i}>
                  <p className="mb-1 text-xs font-medium uppercase tracking-wide text-primary-600">{rp.theme}</p>
                  <PostCard post={post} />
                </div>
              );
            })}
          </div>
        </section>
      )}

      <section className="tp-animate-in rounded-2xl border border-border bg-surface p-6 shadow-sm">
        <h2 className="text-lg font-semibold text-foreground">Collection limitations</h2>
        <p className="mt-2 text-sm text-foreground-muted">{report.limitations}</p>
        <ul className="mt-3 space-y-1 text-xs text-foreground-muted">
          <li>Retrieved {run.retrievedCount} of {run.requestedCount} requested · scored {run.scoredCount} · unscorable {run.unscorableCount}</li>
          <li>
            Similar Content: {run.similarContentPct ?? "n/a"}% across {run.dedupClusterCount} near-duplicate cluster(s)
            {run.similarityMethod ? ` — method: ${run.similarityMethod}, threshold ${run.similarityThreshold}` : ""}. A higher share may indicate
            repetitive or templated posting; it does not by itself prove inauthentic or coordinated activity.
          </li>
          <li>This sample is not necessarily representative of all X users or all discussion of this topic.</li>
        </ul>
      </section>
    </div>
  );
}
